name: Edge Decider (deploy + ping)
on:
  workflow_dispatch:
  push:
    paths:
      - "supabase/functions/global-timer/**"
  schedule:
    - cron: "*/1 * * * *"   # every minute (testing)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - name: Deploy global-timer
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_ID }}   # <-- your secret name
        run: |
          supabase functions deploy global-timer --project-ref "$PROJECT_REF"
          supabase functions list --project-ref "$PROJECT_REF"

  ping:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ping global-timer 6x (~10s cadence)
        run: |
          for i in {1..6}; do
            curl -sS -X GET \
              -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
              -H "apikey: $SUPABASE_ANON_KEY" \
              "$SUPABASE_URL/functions/v1/global-timer" || true
            sleep 10
          done
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}