name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main   # or change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Installs the Supabase CLI correctly (no npm -g)
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # (Optional) Sync function secrets from GitHub → Supabase
      # Add these repo secrets in GitHub:
      #  - SUPABASE_ACCESS_TOKEN
      #  - SUPABASE_PROJECT_ID
      #  - SUPABASE_URL
      #  - SUPABASE_SERVICE_ROLE_KEY
      - name: Set Supabase Function Secrets
        run: |
          supabase secrets set \
            SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
            --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Function
        run: supabase functions deploy dynamic-task --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}