name: Unset Supabase secrets for global-timer

on:
  workflow_dispatch: {}

jobs:
  unset:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: supabase link --project-ref "$PROJECT_REF"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Unset secrets
        run: |
          supabase functions secrets unset \
            --name global-timer \
            SUPABASE_URL \
            SERVICE_ROLE_KEY
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}